### ISSUE TITLE
Sinatra + Docker issues

### ISSUE THREAD

**Issue by singram** [openzipkin/zipkin-ruby#65] opened 2016-05-28 18:59 UTC
I've created a related issue over on Sinatra here but though both projects may benefit from the collaboration. (https://github.com/sinatra/sinatra/issues/1118)

Given a sinatra app.rb of

```
# -*- coding: utf-8 -*-
require 'sinatra'
require 'zipkin-tracer'
set :bind, '0.0.0.0'
use ZipkinTracer::RackHandler, {
      :log_tracing => true,
      :sample_rate =>  1
    }

get '/' do
  "hello world"
end
```

Executing this at the shell via
`bundle exec ruby app.rb`
yields the expected behaviors.  "hello world" is returned and zipkin trace statements are rendered to stdout.

However when executing the same code with same entry point in docker (via docker-compose) none of the zipkin statements are logged to the screen.  Sinatra yields the correct payload and all looks ok, with the exception of the log_tracer behavior.

Any thoughts?

**Comment by jcarres-mdsol** [comment] 2019-03-27 23:50
I'm going to close this. I think the issue is to not be able to write in containers disk

**Closed by jcarres-mdsol** 2019-03-27 23:50 UTC
